In [3]:
# import libraries
from collections import deque
import numpy as np
import random
import random as rand
from matplotlib import pyplot

line_sep = '\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n'


class agentFunction:

    def __init__(self, agentLocation, percept, customerOrder, acutator, randRange):
        self.location = agentLocation
        self.percept = percept
        self.order = customerOrder
        self.orderShelfLocations = []
        self.actuator = actuator
        self.random = randRange

    def setLocation(self, agentLocation):
        self.location = agentLocation

    def getLocation(self):
        return self.location

    def setPercept(self, percept):
        self.percept = percept

    def getPercept(self):
        return self.percept

    def addShelfLocation(self, location):
        self.orderShelfLocations.append(location)

    def getNextShelfLocation(self):
        return self.orderShelfLocations.pop(0)

    def getCurrentShelfLocation(self):
        return self.currentShelf

    def setCurrentShelfLocation(self, location):
        self.currentShelf = location

    # how to handle movement
    # have a current movement?

    def determineAction(self):
        if (self.percept.onOrderShelf()):
            self.actuator.collectItem()
            self.currentShelf = ""
        if (self.percept.shelfCount() == 0):
            if (len(self.orderShelfLocation) == 0):
                move = self.random(4)
                determineRandomMove(move)
            else:
                if (self.currentShelf != ""):
                    self.actuator.move(self.currentShelf)
                else:
                    setCurrentShelfLocation(getNextShelfLocation())
                    self.actuator.move(self.currentShelf)
        elif (self.percept.shelfCount() >= 1):
            shelfLocations = self.percept.getShelfLocations()
            for i in shelfLocations:
                self.addShelfLocation(i)
            self.actuator.move(getNextShelfLocation())

    def determineRandomMove(self, move):
        if (move == 0):
            self.actuator.left()
        elif (move == 1):
            self.actuator.right()
        elif (move == 2):
            self.actuator.up()
        elif (move == 3):
            self.actuator.down()

    # returns true if customer order is complete
    # def hasCollectedAllItems(self):



class Environment:

    def __init__(self):
        self.line_sep = '\n~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n'

        # Define the environment
        self.environment_rows = 6
        self.environment_columns = 6

        self.item_A = 'A'
        self.item_B = 'B'
        self.item_C = 'C'
        self.item_D = 'D'
        self.item_E = 'E'
        self.item_F = 'F'
        self.item_G = 'G'
        self.item_H = 'H'
        self.item_I = 'I'
        self.item_J = 'J'

        self.A = 1, 1
        self.B = 2, 2
        self.C = 3, 1
        self.D = 0, 2
        self.E = 2, 0
        self.F = 4, 2
        self.G = 1, 4
        self.H = 4, 5
        self.I = 2, 4
        self.J = 5, 3

    def print_grid(self, rewards, ordered_items):
        # print itemes ordered
        print(self.line_sep)

        print('======== Customer ordered item[s]  ========')
        print(ordered_items)

        #print(self.line_sep)

        # Print rewards matrix
        print('======== Customer order layout  ========')
        for row in rewards:
            print(row)

        print(self.line_sep)

    def genRandOrder(self):
        x = random.randint(1, 10)
        # Give items their single character name
        items = [self.item_A, self.item_B, self.item_C, self.item_D, self.item_E, self.item_F, self.item_G, self.item_H,
                 self.item_I, self.item_J]

        # Generate random orders containing items A-J
        ordered_items = random.sample(items, x)
        return ordered_items

    # Define rewards
    def buildEnv(self):

        rewards = np.full((self.environment_rows, self.environment_columns), -1)
        ordered_items = self.genRandOrder()

        if self.item_A in ordered_items:
            rewards[self.A] = 3
        else:
            rewards[self.A] = -1

        if self.item_B in ordered_items:
            rewards[self.B] = 3
        else:
            rewards[self.B] = -1

        if self.item_C in ordered_items:
            rewards[self.C] = 3
        else:
            rewards[self.C] = -1

        if self.item_D in ordered_items:
            rewards[self.D] = 3
        else:
            rewards[self.D] = -1

        if self.item_E in ordered_items:
            rewards[self.E] = 3
        else:
            rewards[self.E] = -1

        if self.item_F in ordered_items:
            rewards[self.F] = 3
        else:
            rewards[self.F] = -1

        if self.item_G in ordered_items:
            rewards[self.G] = 3
        else:
            rewards[self.G] = -1

        if self.item_H in ordered_items:
            rewards[self.H] = 3
        else:
            rewards[self.H] = -1

        if self.item_I in ordered_items:
            rewards[self.I] = 3
        else:
            rewards[self.I] = -1

        if self.item_J in ordered_items:
            rewards[self.J] = 3
        else:
            rewards[self.J] = -1

        return rewards, ordered_items

        # Print rewards matrix


class actuator:
    def __init__(self):
        print("a")

    def collectItem(self):
        print("a")

    def move(self):
        print("a")

    def left(self):
        print("a")

    def right(self):
        print("a")

    def up(self):
        print("a")

    def down(self):
        print("a")

    def addVisitedSpace(self):
        print("a")


class percept:
    def __init__(self, currentLocation, envArray):
        self.percepts = dict(left=dict(coord=[], value=""), right=dict(coord=[], value=""), up=dict(coord=[], value=""),
                             down=dict(coord=[], value=""), current=dict(coord=[], value=""))
        self.currentLocation = currentLocation
        self.envArray = envArray

    def determine(self):

        self.percepts["current"]["coord"] = self.currentLocation
        self.percepts["current"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]

        if (self.currentLocation[0] == 0):
            self.percepts["up"]["coord"] = []
            self.percepts["up"]["value"] = ""
        else:
            self.percepts["up"]["coord"] = [(self.currentLocation[0] - 1), self.currentLocation[1]]
            self.percepts["up"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]

        if (self.currentLocation[0] == 5):
            self.percepts["down"]["coord"] = []
            self.percepts["down"]["value"] = ""
        else:
            self.percepts["down"]["coord"] = [(self.currentLocation[0] + 1), self.currentLocation[1]]
            self.percepts["down"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]

        if (self.currentLocation[1] == 0):
            self.percepts["left"]["coord"] = []
            self.percepts["left"]["value"] = ""
        else:
            self.percepts["left"]["coord"] = [self.currentLocation[0], (self.currentLocation[1] - 1)]
            self.percepts["left"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]

        if (self.currentLocation[1] == 5):
            self.percepts["right"]["coord"] = []
            self.percepts["right"]["value"] = ""
        else:
            self.percepts["right"]["coord"] = [self.currentLocation[0], (self.currentLocation[1] + 1)]
            self.percepts["right"]["value"] = self.envArray[self.currentLocation[0]][self.currentLocation[1]]

    def onOrderShelf(self):
        if (self.percepts["current"]["value"] == 3):
            return True;
        return False

    def shelfCount(self):
        count = 0
        for i in self.percepts:
            if i["value"] == 3:
                count = count + 1
        return count

    def getShelfLocations(self):
        shelves = []
        for i in self.percepts:
            if i["value"] == 3:
                shelves.append(i["coord"])
        return shelves

    def getPercepts(self):
        return self.percepts

    def setValue(self, key, value):
        self.percepts[key]['value'] = value


class sensor:
    def __init__(self, random, agentlocation, percept):
        self.random = random
        self.agentlocation = agentlocation
        self.percept = percept

    def sensorRoll(self):
        roll = self.random.randint(1, 10)
        if roll == 9:
            percepts = self.percept.getPercepts()
            percepts = self.setEmptyShelf()
        elif roll == 10:
            percepts = self.percept.getPercepts()
            percepts = self.setShelf()

    # need the percept to be an array of dictionaries
    def setEmptyShelf(self):
        shelves = []
        for i in self.percept.getPercepts():
            if (self.percept.getPercepts()[i]['value'] == 3):
                if (i != 'current'):
                    shelves.append(i)
        if (len(shelves) > 0):
            roll = self.random.randint(0, (len(shelves) - 1))
            key = shelves[roll]
            self.percept.setValue(key, -1)

    def setShelf(self):
        empty = []
        for i in self.percept.getPercepts():
            if (self.percept.getPercepts()[i]['value'] == -1):
                if (i != 'current'):
                    empty.append(i)
        if (len(empty) > 0):
            roll = self.random.randint(0, (len(empty) - 1))
            key = empty[roll]
            self.percept.setValue(key, 3)


class stats:
    def __init__(self, percept):
        self.percept = percept
        self.score = 0

    def updateScore(self):
        self.score = self.score + self.percept["current"]["value"]

    def getScore(self):
        return self.score


def main():
    env = Environment()
    warehouse, ordered_items = env.buildEnv()
    env.print_grid(warehouse, ordered_items)

    # agentLocation starts at 0,0 in first episode
    agentLocation = [0, 0]
    prcpt = percept(agentLocation, warehouse)

    determine = prcpt.determine()
    snsr = sensor(rand, agentLocation, prcpt)
    snsr.sensorRoll()
    act = actuator()
    agent = agentFunction(agentLocation, prcpt, ordered_items, act, rand)
    # while(!agent.hasCollectedAllItems()) {

    # }


if __name__ == "__main__":
    main()

env = Environment()
warehouse, ordered_items = env.buildEnv()
#env.print_grid(warehouse, ordered_items)

# agentLocation starts at 0,0 in first episode
agentLocation = [0, 0]

prcpt = percept(agentLocation, warehouse)
determine = prcpt.determine()
print(prcpt.getPercepts())

snsr = sensor(rand, agentLocation, prcpt)
snsr.setShelf()
print(prcpt.getPercepts())



~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

======== Customer ordered item[s]  ========
['D']
======== Customer order layout  ========
[-1 -1  3 -1 -1 -1]
[-1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1]
[-1 -1 -1 -1 -1 -1]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

a
{'left': {'coord': [], 'value': ''}, 'right': {'coord': [0, 1], 'value': -1}, 'up': {'coord': [], 'value': ''}, 'down': {'coord': [1, 0], 'value': -1}, 'current': {'coord': [0, 0], 'value': -1}}
{'left': {'coord': [], 'value': ''}, 'right': {'coord': [0, 1], 'value': -1}, 'up': {'coord': [], 'value': ''}, 'down': {'coord': [1, 0], 'value': 3}, 'current': {'coord': [0, 0], 'value': -1}}
